name: fasten_stitch_element_flutter
description: A Flutter SDK for embedding the Fasten Connect Stitch experience in native apps.
version: 1.0.0
homepage: https://github.com/fastenhealth/fasten-stitch-element-flutter
repository: https://github.com/fastenhealth/fasten-stitch-element-flutter
issue_tracker: https://github.com/fastenhealth/fasten-stitch-element-flutter/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

topics:
  - fasten
  - healthcare
  - webview
  - oauth
  - sdk

